name: Check if commits are promoted

on:
  push:
    branches:
      - master
      - branch-*.*
      - enterprise
  pull_request_target:
    types: [labeled, unlabeled]
    branches: [master, next, enterprise]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set Default Branch
        id: set_branch
        run: |
          if [[ "${{ github.repository }}" == *enterprise* ]]; then
            echo "DEFAULT_BRANCH=enterprise" >> $GITHUB_ENV
          else
            echo "DEFAULT_BRANCH=master" >> $GITHUB_ENV
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.DEFAULT_BRANCH }}
          token: ${{ secrets.AUTO_BACKPORT_TOKEN }}
          fetch-depth: 0  # Fetch all history for all tags and branches
      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global merge.conflictstyle diff3
      - name: Install dependencies
        run: sudo apt-get install -y python3-github python3-git
      - name: Run python script
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: python .github/scripts/label_promoted_commits.py  --commits ${{ github.event.before }}..${{ github.sha }} --repository ${{ github.repository }} --ref ${{ github.ref }}
      - name: Run auto-backport.py when promotion completed
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', env.DEFAULT_BRANCH) }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: python .github/scripts/auto-backport.py --repo ${{ github.repository }} --base-branch ${{ github.ref }} --commits ${{ github.event.before }}..${{ github.sha }}
      - name: Check if label starts with 'backport/' and contains digits
        id: check_label
        run: |
          label_name="${{ github.event.label.name }}"
          if [[ "$label_name" =~ ^backport/[0-9]+\.[0-9]+$ ]]; then
            echo "Label matches backport/X.X pattern."
            echo "backport_label=true" >> $GITHUB_OUTPUT
          else
            echo "Label does not match the required pattern."
            echo "backport_label=false" >> $GITHUB_OUTPUT
          fi
      - name: check if 'scylladbbot/backport_error' label was removed
        id: check_backport_error_label
        run: |
          label_name="${{ github.event.label.name }}"
          if [[ "$label_name" == scylladbbot/backport_error ]]; then
            echo "backport_error_label_removed=false" >> $GITHUB_OUTPUT
          else
            echo "backport_error_label_removed=true" >> $GITHUB_OUTPUT
          fi
      - name: Run auto-backport.py when label was added
        if: ${{ github.event_name == 'pull_request_target' && steps.check_label.outputs.backport_label == 'true' && github.event.pull_request.state == 'closed' && steps.check_backport_error_label.outputs.backport_error_label_removed == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: python .github/scripts/auto-backport.py --repo ${{ github.repository }} --base-branch ${{ github.ref }} --pull-request ${{ github.event.pull_request.number }} --head-commit ${{ github.event.pull_request.base.sha }}
