name: Check if commits are promoted

on:
  push:
    branches:
      - master
      - next-*.*
  pull_request_target:
    types: [labeled, closed]
    branches: [master, next, next-*.*]

env:
  DEFAULT_BRANCH: 'master'

jobs:
  check-commit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.DEFAULT_BRANCH }}
          token: ${{ secrets.AUTO_BACKPORT_TOKEN }}
          fetch-depth: 0  # Fetch all history for all tags and branches
      - name: Set up Git identity
        run: |
          git config --global user.name "scylladbbot"
          git config --global user.email "scylladbbot@scylladb.com"
          git config --global merge.conflictstyle diff3
      - name: Install dependencies
        run: sudo apt-get install -y python3-github python3-git
      - name: Run python script
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: python .github/scripts/search_commits.py  --commits ${{ github.event.before }}..${{ github.sha }} --repository ${{ github.repository }} --ref ${{ github.ref }}
      - name: Run auto-backport.py when promotion completed
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', env.DEFAULT_BRANCH)
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: python .github/scripts/auto-backport.py --repo ${{ github.repository }} --base-branch ${{ github.ref }} --commits ${{ github.event.before }}..${{ github.sha }}
      - name: Check if label starts with 'backport/' and contains digits
        id: check_label
        run: |
          label_name="${{ github.event.label.name }}"
          if [[ "$label_name" =~ ^backport/[0-9]+\.[0-9]+$ ]]; then
            echo "Label matches backport/X.X pattern."
            echo "backport_label=true" >> $GITHUB_OUTPUT
          else
            echo "Label does not match the required pattern."
            echo "backport_label=false" >> $GITHUB_OUTPUT
          fi
      - name: Run auto-backport.py when label was added
        if: github.event_name == 'pull_request_target' && steps.check_label.outputs.backport_label == 'true' && github.event.pull_request.state == 'closed'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: python .github/scripts/auto-backport.py --repo ${{ github.repository }} --base-branch ${{ github.ref }} --pull-request ${{ github.event.pull_request.number }} --head-commit ${{ github.event.pull_request.base.sha }} --label ${{ github.event.label.name }}
      # Handle waterfall backporting when a backport PR is merged
      - name: Check if this is a merged backport PR
        id: check_backport_pr
        if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          if [[ "$pr_title" =~ ^\[Backport[[:space:]][0-9]+\.[0-9]+\] ]]; then
            echo "Is a backport PR"
            echo "is_backport=true" >> $GITHUB_OUTPUT
          else
            echo "Not a backport PR"
            echo "is_backport=false" >> $GITHUB_OUTPUT
          fi
      - name: Process waterfall backport for merged backport PR
        if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && steps.check_backport_pr.outputs.is_backport == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: |
          echo "Processing waterfall backport for merged PR #${{ github.event.pull_request.number }}"
          python .github/scripts/auto-backport.py --repo ${{ github.repository }}
